openapi: 3.0.3
info:
  title: test
  description: test
  version: "1.0"
servers:
- url: http://0.0.0.0:80
  description: tets
  variables:
    version:
      default: v1
paths:
  /costs:
    get:
      tags:
      - channel
      summary: UpdateChannelCostStatus channel
      operationId: channel#UpdateChannelCostStatus
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateChannelCostStatusRequestBody'
            example:
              country_codes:
              - US
              - UK
              ids:
              - 1
              - 2
              status: true
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateChannelCostStatusRsp'
              example:
                code: 0
                data:
                  status: 1
                message: description error information
        "401":
          description: Unauthorized response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
      security:
      - jwt_header_Authorization:
        - api:read
        - api:write
components:
  schemas:
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: false
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    UpdateChannelCostStatusRequestBody:
      type: object
      properties:
        country_codes:
          type: array
          items:
            type: string
            example: Tempore quas aut maxime aut.
          description: 排除国际二字码
          example:
          - US
          - UK
        ids:
          type: array
          items:
            type: integer
            example: 5182999267236941882
            format: int64
          description: 渠道ID
          example:
          - 1
          - 2
        status:
          type: boolean
          description: 状态（0 不启用 1 启用）
          example: true
          enum:
          - false
          - true
      example:
        country_codes:
        - US
        - UK
        ids:
        - 1
        - 2
        status: true
      required:
      - ids
      - country_codes
      - status
    UpdateChannelCostStatusRsp:
      type: object
      properties:
        code:
          type: integer
          description: code
          example: 0
          format: int64
        data:
          $ref: '#/components/schemas/UpdateCustomerConfigData'
        message:
          type: string
          description: message
          example: description error information
      example:
        code: 0
        data:
          status: 1
        message: description error information
      required:
      - code
      - message
    UpdateCustomerConfigData:
      type: object
      properties:
        status:
          type: integer
          description: 状态（0 更新成功 1 更新失败）
          example: 1
          format: int32
      example:
        status: 1
      required:
      - status
  securitySchemes:
    jwt_header_Authorization:
      type: http
      description: Secures endpoint by requiring a valid JWT token retrieved via the
        signin endpoint
      scheme: bearer
tags:
- name: channel
  description: The quote service performs operations on quotation
